theme: jekyll-theme-cayman
title: HAPi DevOps 2022
description: |- 
  1st International Workshop on Human-Centric Approaches and Practices for DevOps
  
  Bringing together the DevOps and VL/HCC communities. The former can identify outstanding issues clearly and the latter to understand them, start thinking about how to help in solving existing challenges and point to possible paths or solutions.
github:
  is_project_page: false
