theme: jekyll-theme-cayman
title: HAPi DevOps
description: | 
  1st International Workshop on Human-Centric Approaches and Practices for DevOps
  We seek to bring together the DevOps and the VL/HCC and related communities so the former can identify outstanding issues clearly and the latter to understand them, start thinking about how to help in solving existing challenges and point to possible paths or solutions.
github:
  is_project_page: false
