theme: jekyll-theme-cayman
title: HAPi DevOps 2022
description: |- 
  1st International Workshop on Human-Centric Approaches and Practices for DevOps
  
  Co-located with [VL/HCC](https://conf.researchr.org/home/vlhcc-2022), the workshop brings together the DevOps and HCI communities, to clearly identify outstanding issues in DevOps, understand them, reflect on how to solve such challenges and point to possible paths or solutions.
github:
  is_project_page: false
